### ISSUE TITLE
Error while generating class images

### ISSUE THREAD

**Issue by InB4DevOps** [ShivamShrirao/diffusers#10]
### Describe the bug

```
(diffusers) user@powerpc:~/github/diffusers/examples/dreambooth$ ./my_training.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Fetching 16 files: 100%|█████████████████████████████████████████████████████████████| 16/16 [00:00<00:00, 16221.63it/s]
Generating class images:   0%|                                                                   | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/github/diffusers/examples/dreambooth/train_dreambooth.py", line 658, in <module>
    main()
  File "/home/user/github/diffusers/examples/dreambooth/train_dreambooth.py", line 389, in main
    with context:
AttributeError: __enter__
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: 
Command '['/home/user/anaconda3/envs/diffusers/bin/python', 
'train_dreambooth.py', 
'--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', 
'--use_auth_token', 
'--instance_data_dir=training', 
'--with_prior_preservation', 
'--prior_loss_weight=1.0', 
'--instance_prompt=a photo of a dog', 
'--class_prompt=a photo of dog', 
'--resolution=512', 
'--train_batch_size=1', 
'--gradient_accumulation_steps=2', 
'--gradient_checkpointing', 
'--use_8bit_adam', 
'--learning_rate=5e-6', 
'--lr_scheduler=constant', 
'--lr_warmup_steps=0', 
'--max_train_steps=800', 
'--class_data_dir=classes']' returned non-zero exit status 1.
```

### Reproduction

Using this shell script I get the error above: 

```
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="training"
export OUTPUT_DIR="my_model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME --use_auth_token \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of a dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=2 --gradient_checkpointing \
  --use_8bit_adam \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 --max_train_steps=800 \
  --class_data_dir="classes"
  ```

### System Info

Ubuntu on WSL, 12GB 3060

**Comment by ShivamShrirao** [comment]
Hi, I think we discussed the same on reddit. It seems your CUDA installation and/or the GPU is not being detected in WSL.

**Comment by InB4DevOps** [comment]
That's actually what I also just found out. Do you have a reddit link for me please so I can read along?

**Comment by ShivamShrirao** [comment]
@InB4DevOps here https://www.reddit.com/r/StableDiffusion/comments/xtc25y/comment/iqxl54g/

**Comment by InB4DevOps** [comment]
Turns out my Ubuntu on WSL was version 1 although the default version was set to 2. 🤷‍♂️ 
`wsl -l -v`

make sure your distro is version 2
