### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x2560 and 320x320)

### ISSUE THREAD

**Issue by geocine** [ShivamShrirao/diffusers#101]
### Describe the bug

Rnning the default `launch.sh` under `diffusers/examples/dreambooth` results in the following error 
```
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x2560 and 320x320)
```

### Reproduction

**concepts_list.json**
```json
[
    {
        "instance_prompt":      "photo of zwx dog",
        "class_prompt":         "photo of a dog",
        "instance_data_dir":    "./images",
        "class_data_dir":       "./class_images/dog"
    }
]
```
**launch.sh**
```sh
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export OUTPUT_DIR="./output"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_name_or_path="stabilityai/sd-vae-ft-mse" \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --seed=3434554 \
  --resolution=512 \
  --train_batch_size=1 \
  --train_text_encoder \
  --mixed_precision="fp16" \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=1e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=50 \
  --sample_batch_size=4 \
  --max_train_steps=800 \
  --save_interval=400 \
  --save_sample_prompt="photo of zwx dog" \
  --concepts_list="concepts_list.json"
```

1. Change directory to `diffusers/examples/dreambooth`
2. Run `pip install git+https://github.com/ShivamShrirao/diffusers.git`
3. Run `pip install -U -r requirements.txt`
4. accelerate config -> 0, 0, No, No, fp16
5. `huggingface-cli login` <- Enter Token
6. Download avlan images from README crop it to 512x512 and put it on `./images` folder
7. Run `launch.sh` <-- Problem stops at Generating class images, check logs

### Logs

```shell
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `16` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[!] Not using xformers memory efficient attention.
Fetching 15 files: 100%|█████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 71984.62it/s]
You have passed `None` for safety_checker to disable its functionality in <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>. Note that this might lead to problems when using <class 'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'> and is not recommended.
Generating class images:   0%|                                                                   | 0/13 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train_dreambooth.py", line 805, in <module>
    main(args)
  File "train_dreambooth.py", line 463, in main
    images = pipeline(example["prompt"]).images
  File "/home/s9/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 344, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 296, in forward
    sample, res_samples = downsample_block(
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 563, in forward
    hidden_states = attn(hidden_states, context=encoder_hidden_states)
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/diffusers/models/attention.py", line 169, in forward
    hidden_states = block(hidden_states, context=context)
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/diffusers/models/attention.py", line 217, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/diffusers/models/attention.py", line 296, in forward
    return self.to_out(hidden_states)
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/s9/.local/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (4096x2560 and 320x320)
Traceback (most recent call last):
  File "/home/s9/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/s9/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/s9/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/s9/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=./output', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=3434554', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=4', '--max_train_steps=800', '--save_interval=400', '--save_sample_prompt=photo of zwx dog', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.
```

### System Info

Tested at 7465397f33d5de75dcccc155e3fb9a232fcbb0a0

```
WSL version: 0.70.4.0
Kernel version: 5.15.68.1
WSLg version: 1.0.45
MSRDC version: 1.2.3575
Direct3D version: 1.606.4
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.674
```

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

```
Python 3.8.10
```

```
Package                  Version
------------------------ --------------------
absl-py                  1.3.0
accelerate               0.12.0
attrs                    19.3.0
Automat                  0.8.0
blinker                  1.4
cachetools               5.2.0
certifi                  2019.11.28
chardet                  3.0.4
Click                    7.0
cloud-init               21.4
colorama                 0.4.3
command-not-found        0.3
configobj                5.0.6
constantly               15.1.0
cryptography             2.8
dbus-python              1.2.16
diffusers                0.7.0.dev0
distro                   1.4.0
distro-info              0.23ubuntu1
entrypoints              0.3
filelock                 3.8.0
ftfy                     6.1.1
google-auth              2.13.0
google-auth-oauthlib     0.4.6
grpcio                   1.50.0
httplib2                 0.14.0
huggingface-hub          0.10.1
hyperlink                19.0.0
idna                     2.8
importlib-metadata       5.0.0
incremental              16.10.1
Jinja2                   2.10.1
jsonpatch                1.22
jsonpointer              2.0
jsonschema               3.2.0
keyring                  18.0.1
language-selector        0.1
launchpadlib             1.10.13
lazr.restfulclient       0.14.2
lazr.uri                 1.0.3
Markdown                 3.4.1
MarkupSafe               2.1.1
modelcards               0.1.6
more-itertools           4.2.0
netifaces                0.10.4
numpy                    1.23.4
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.1.0
packaging                21.3
pexpect                  4.6.0
Pillow                   9.3.0
pip                      20.0.2
protobuf                 3.19.6
psutil                   5.9.3
pyasn1                   0.4.2
pyasn1-modules           0.2.1
PyGObject                3.36.0
PyHamcrest               1.9.0
PyJWT                    1.7.1
pymacaroons              0.13.0
PyNaCl                   1.3.0
pyOpenSSL                19.0.0
pyparsing                3.0.9
pyrsistent               0.15.5
pyserial                 3.4
python-apt               2.0.0+ubuntu0.20.4.7
python-debian            0.1.36ubuntu1
PyYAML                   5.3.1
regex                    2022.9.13
requests                 2.22.0
requests-oauthlib        1.3.1
requests-unixsocket      0.2.0
rsa                      4.9
SecretStorage            2.3.1
service-identity         18.1.0
setuptools               45.2.0
simplejson               3.16.0
six                      1.14.0
sos                      4.2
ssh-import-id            5.10
systemd-python           234
tensorboard              2.10.1
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
tokenizers               0.13.1
torch                    1.12.1+cu116
torchvision              0.13.1+cu116
tqdm                     4.64.1
transformers             4.23.1
Twisted                  18.9.0
typing-extensions        4.4.0
ubuntu-advantage-tools   27.6
ufw                      0.36
unattended-upgrades      0.1
urllib3                  1.25.8
wadllib                  1.3.3
wcwidth                  0.2.5
Werkzeug                 2.2.2
wheel                    0.34.2
zipp                     1.0.0
zope.interface           4.7.1
```

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:36:24_Pacific_Standard_Time_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
```

**Comment by ShivamShrirao** [comment]
Fixed in 1b1f2431d4bb5a40145d5fd5633f16065e594698
