### ISSUE TITLE
Error caused by reg_images/images not being a tensor during start of training

### ISSUE THREAD

**Issue by thojmr** [ShivamShrirao/diffusers#11]
### Describe the bug

Something is going wrong with my reg class images during training when running with `--with_prior_preservation`
I can train just fine without `--with_prior_preservation` on the same images
Using latest code.  Any ideas?

```
Traceback (most recent call last):
  File "train_dreambooth.py", line 658, in <module>
    main()
  File "train_dreambooth.py", line 605, in main
    noise_pred, noise_pred_prior = torch.chunk(noise_pred, 2, dim=0)
TypeError: chunk(): argument 'input' (position 1) must be Tensor, not dict
```

### Reproduction

Here are my training params

```sh
accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path="../models/" \
  --instance_data_dir="../images/${FOLDER}" \
  --class_data_dir="../images/${REG_FOLDER}" \
  --output_dir="./output" \
  --with_prior_preservation \
  --instance_prompt="${KEYWORD}" \
  --class_prompt="${REG_KEYWORD}" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=92 \
  --max_train_steps=${STEPS} \
  --mixed_precision="fp16" \
  --not_cache_latents
```

### Logs

```shell
I can verify the images and reg_images are both loading into dataloader
```

### System Info

diffusers               0.3.0
torch                   1.10.1+cu111
python 3.8

Using WSL2 on windows

**Comment by thojmr** [comment]
Was able to bypass it this error by changing line 606 to `noise_pred["sample"]` instead of `noise_pred`.

But it looks like Ill have to stick to no prior preservation as I OOM on WSL with `--with_prior_preservation` enabled
