### ISSUE TITLE
DeepSpeed Failed with exit codes 245 and -11

### ISSUE THREAD

**Issue by 78Alpha** [ShivamShrirao/diffusers#112]
### Describe the bug

When launching the training as described in the README for 8 GB GPUs the script eventually stops... and that's about it. It doesn't really say why other than an exit code of 245 (accelerate 0.12.0 @ line 540 of launch.py) or -11 (accelerate 0.13.2). I have looked into the launch.py that the error says it came from and the only description I have found was 

`    if process.returncode != 0:
        raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)`

The equivalent of _If ERROR, then ERROR_

### Reproduction

1.) Follow the installation guide
2.) Configure Accelerate with DeepSpeed enabled
3.) Run using the template with your own directories...

```
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="path-to-instance-images"
export CLASS_DIR="path-to-class-images"
export OUTPUT_DIR="path-to-save-model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="a photo of sks dog" \
  --class_prompt="a photo of dog" \
  --resolution=512 \
  --train_batch_size=1 \
  --sample_batch_size=1 \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=200 \
  --max_train_steps=800 \
  --mixed_precision=fp16
```

### Logs

```shell
Accelerate 0.13.2
`Caching latents: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 200/200 [00:31<00:00,  6.32it/s]
[2022-11-03 20:05:46,849] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.7.4, git-hash=unknown, git-branch=unknown
/home/alpha78/.local/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py:429: UserWarning: torch.distributed.distributed_c10d._get_global_rank is deprecated please use torch.distributed.distributed_c10d.get_global_rank instead
  warnings.warn(
[2022-11-03 20:05:47,493] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2022-11-03 20:05:47,493] [INFO] [logging.py:68:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2022-11-03 20:05:47,493] [INFO] [logging.py:68:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2022-11-03 20:05:47,544] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Basic Optimizer = AdamW
[2022-11-03 20:05:47,544] [INFO] [utils.py:52:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'torch.optim.adamw.AdamW'>
[2022-11-03 20:05:47,544] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 2 optimizer
[2022-11-03 20:05:47,544] [INFO] [stage_1_and_2.py:140:__init__] Reduce bucket size 500000000
[2022-11-03 20:05:47,544] [INFO] [stage_1_and_2.py:141:__init__] Allgather bucket size 500000000
[2022-11-03 20:05:47,544] [INFO] [stage_1_and_2.py:142:__init__] CPU Offload: True
[2022-11-03 20:05:47,544] [INFO] [stage_1_and_2.py:143:__init__] Round robin gradient partitioning: False
Using /home/alpha78/.cache/torch_extensions/py38_cu117 as PyTorch extensions root...
Emitting ninja build file /home/alpha78/.cache/torch_extensions/py38_cu117/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.12659978866577148 seconds
Rank: 0 partition count [1] and sizes[(859520964, False)]
[2022-11-03 20:05:49,892] [INFO] [utils.py:827:see_memory_usage] Before initializing optimizer states
[2022-11-03 20:05:49,893] [INFO] [utils.py:828:see_memory_usage] MA 1.73 GB         Max_MA 5.13 GB         CA 3.34 GB         Max_CA 5 GB
[2022-11-03 20:05:49,893] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 8.49 GB, percent = 22.6%
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 4884) of binary: /usr/bin/python3`

Accelerate 0.12.0

`[2022-11-03 20:14:47,288] [INFO] [utils.py:827:see_memory_usage] Before initializing optimizer states
[2022-11-03 20:14:47,288] [INFO] [utils.py:828:see_memory_usage] MA 1.73 GB         Max_MA 5.13 GB         CA 3.34 GB         Max_CA 5 GB
[2022-11-03 20:14:47,289] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 8.82 GB, percent = 23.5%
[2022-11-03 20:14:49,076] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 5014
[2022-11-03 20:14:49,076] [ERROR] [launch.py:292:sigkill_handler] ['/usr/bin/python3', '-u', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=/mnt/i/DataSets/test', '--class_data_dir=/mnt/i/DataSets/test', '--output_dir=/mnt/i/trainingmodel', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks test', '--class_prompt=a photo of test', '--resolution=512', '--train_batch_size=1', '--sample_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800', '--mixed_precision=fp16'] exits with return code = -11
Traceback (most recent call last):
  File "/home/alpha78/.local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/alpha78/.local/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/alpha78/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 827, in launch_command
    deepspeed_launcher(args)
  File "/home/alpha78/.local/lib/python3.8/site-packages/accelerate/commands/launch.py", line 540, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--num_gpus', '1', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=/mnt/i/DataSets/test', '--class_data_dir=/mnt/i/DataSets/test', '--output_dir=/mnt/i/trainingmodel', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks test', '--class_prompt=a photo of test', '--resolution=512', '--train_batch_size=1', '--sample_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800', '--mixed_precision=fp16']' returned non-zero exit status 245.`
```

### System Info

Python 3.8.10
Diffusers 0.7.0.dev0
Windows 10 + Ubuntu WSL2
Ryzen 7 3700x
48 GB RAM
RTX 3070 8 GB

**Comment by 78Alpha** [comment]
Looking even further and just running DepSpeed myself, it appears to be an Out of Memory issue... so 8 GB may not be possible.

**Comment by 78Alpha** [comment]
Reducing the resolution actually seems to raise the memory I run out of. With 512x512 it fails with OOM 30MiB, but with 256x256 it fails with OOM 58 MiB
