### ISSUE TITLE
 RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

### ISSUE THREAD

**Issue by rexroth0619** [ShivamShrirao/diffusers#117]
### Describe the bug

Suddenly appeared one day (successfully trained numerous models already). 
I checked pytorch forum and they say it's because "weights are on GPU but inputs are on CPU", or a "mismatch of devices", but I have no idea how to fix it, since we are only using train_dreambooth.py here...

### Logs

```shell
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `20` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/opt/conda/lib/python3.7/site-packages/accelerate/accelerator.py:179: UserWarning: `log_with=tensorboard` was passed but no supported trackers are currently installed.
  warnings.warn(f"`log_with={log_with}` was passed but no supported trackers are currently installed.")
Caching latents: 100%|████████████████████████| 100/100 [00:18<00:00,  5.31it/s]
Steps:   0%|                                          | 0/12000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 811, in <module>
    main(args)
  File "train_dreambooth.py", line 757, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py", line 301, in forward
    sample = self.conv_in(sample)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.cuda.HalfTensor) should be the same
Steps:   0%|                                          | 0/12000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=/workspace/nd_model', '--output_dir=/workspace/sd_weights/sks/homunculus-1e6', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=no', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=2e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=4', '--max_train_steps=12000', '--save_interval=2000', '--save_sample_prompt=1girl, sks homunculus style', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.
```

### System Info

- `diffusers` version: 0.8.0.dev0
- Platform: Linux-5.4.0-122-generic-x86_64-with-debian-buster-sid
- Python version: 3.7.13
- PyTorch version (GPU?): 1.12.0 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.24.0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by ShivamShrirao** [comment]
Are u running locally ?

Did u download new version recently ? Did u upgrade the diffusers package ?

**Comment by rexroth0619** [comment]
Hi, thanks for the reminder actually -- I'm indeed running "locally" on runpod.io. The train_dreambooth.py version I'm using is from 4 days ago -- and that seemed to be the problem.

Just deleted it and downloaded a new one and the code started to run. Looks like I'll have to make some adjustment to the code to make sure a new version of train_dreambooth is downloaded every time, since it's a local installment
