### ISSUE TITLE
Dreambooth script fails due to incorrect argument type

### ISSUE THREAD

**Issue by nosajthenitram** [ShivamShrirao/diffusers#119]
### Describe the bug

When running the dreambooth script, I encounter the following: 

Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.HalfTensor instead (while checking arguments for embedding)

### Reproduction

accelerate config

In which compute environment are you running? ([0] This machine, [1] AWS (Amazon SageMaker)): 0
Which type of machine are you using? ([0] No distributed training, [1] multi-CPU, [2] multi-GPU, [3] TPU [4] MPS): 0
Do you want to run your training on CPU only (even if a GPU is available)? [yes/NO]: NO
Do you want to use DeepSpeed? [yes/NO]: yes
Do you want to specify a json file to a DeepSpeed config? [yes/NO]: NO
What should be your DeepSpeed's ZeRO optimization stage (0, 1, 2, 3)? [2]: 2
Where to offload optimizer states? [none/cpu/nvme]: cpu
Where to offload parameters? [none/cpu/nvme]: cpu
How many gradient accumulation steps you're passing in your script? [1]:
Do you want to use gradient clipping? [yes/NO]: NO
Do you want to enable `deepspeed.zero.Init` when using ZeRO Stage-3 for constructing massive models? [yes/NO]: NO
How many GPU(s) should be used for distributed training? [1]:1
Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]: fp16

### Logs

```shell
Traceback (most recent call last):
  File "/home/public/ml/github/diffusers/examples/dreambooth/train_dreambooth.py", line 824, in <module>
    main(args)
  File "/home/public/ml/github/diffusers/examples/dreambooth/train_dreambooth.py", line 763, in main
    encoder_hidden_states = text_encoder(batch[0][1])[0]
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 733, in forward
    return self.text_model(
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 636, in forward
    hidden_states = self.embeddings(input_ids=input_ids, position_ids=position_ids)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/transformers/models/clip/modeling_clip.py", line 165, in forward
    inputs_embeds = self.token_embedding(input_ids)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/modules/sparse.py", line 160, in forward
    return F.embedding(
  File "/home/public/anaconda3/envs/dreambooth/lib/python3.9/site-packages/torch/nn/functional.py", line 2210, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.HalfTensor instead (while checking arguments for embedding)
```

### System Info

python: 3.9
diffusers: 0.8.0-dev
transformers: 4.24.0

**Comment by LJ-Zhang** [comment]
I met the same problem, have you solved it yet? @nosajthenitram
