### ISSUE TITLE
DreamBooth training error | RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by ProGamerGov** [ShivamShrirao/diffusers#123]
### Describe the bug

The bug occured while training with the DreamBooth script on a VM using full precision. 

```
export MODEL_NAME="runwayml/stable-diffusion-v1-5"
export VAE_NAME="stabilityai/sd-vae-ft-mse"
export INSTANCE_DIR="instance-path"
export CLASS_DIR="class-path"
export OUTPUT_DIR="path-to-save-model"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME \
  --pretrained_vae_name_or_path=$VAE_NAME \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="concept" \
  --class_prompt="concept" \
  --save_sample_prompt="concept" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=2000 \
  --save_interval=500 \
  --max_train_steps=4000 \
  --train_text_encoder \
  --mixed_precision="no" \
  --seed=8008 \
  --not_cache_latents
```

It works in https://github.com/ShivamShrirao/diffusers/commit/3cb0dbe8e407cffbba242ed3412e8359f34d9a33, but not in the latest commit. It also works in: https://github.com/ShivamShrirao/diffusers/commit/c28895aedaa5d9316e42a380723ea472cf6a0e8e

### Logs

```shell
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `6` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Downloading: 100%|████████████████████████████| 335M/335M [00:03<00:00, 105MB/s]
Downloading: 100%|██████████████████████████████| 547/547 [00:00<00:00, 626kB/s]
Generating samples:   0%|                                 | 0/4 [00:00<?, ?it/s]
Traceback (most recent call last):                        | 0/4 [00:00<?, ?it/s]
  File "train_dreambooth.py", line 824, in <module>
    main(args)
  File "train_dreambooth.py", line 807, in main
    save_weights(global_step)
  File "train_dreambooth.py", line 713, in save_weights
    images = pipeline(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 389, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/models/unet_2d_condition.py", line 307, in forward
    sample, res_samples = downsample_block(
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/models/unet_2d_blocks.py", line 598, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention.py", line 204, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention.py", line 406, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/diffusers/models/attention.py", line 503, in forward
    hidden_states = self.to_out[0](hidden_states)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
Steps:   2%|▏         | 500/25000 [07:55<6:28:24,  1.05it/s, loss=0.27, lr=1e-6]
Traceback (most recent call last):
  File "/opt/conda/envs/ldm/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/opt/conda/envs/ldm/lib/python3.8/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/ldm/bin/python', 'train_dreambooth.py',
```
```


### System Info

N/A

**Comment by ShivamShrirao** [comment]
Now 674823c8e4582868e7f30682868dcd216c9972f8 ?

**Comment by ProGamerGov** [comment]
@ShivamShrirao I'm going to have to wait to test it until my current training session with the the https://github.com/ShivamShrirao/diffusers/commit/c28895aedaa5d9316e42a380723ea472cf6a0e8e version of `train_dreambooth.py` is done.

**Comment by ProGamerGov** [comment]
@ShivamShrirao The error appears to be resolved.
