### ISSUE TITLE
Cannot Run the Colab Version

### ISSUE THREAD

**Issue by SingingTurnip** [ShivamShrirao/diffusers#14]
### Describe the bug

I get a huge error when I fill in the steps as shown on the video by James Cunliffe here: https://www.youtube.com/watch?v=FaLTztGGueQ 

I have posted the error below and the colab was a Tesla T4, 15109 MiB

This error occurs when I press "play" on the "Start Training" section.

### Reproduction

Follow his steps to the letter, except change his "realjames" for something else like whatever you called your Hugging Face token.

This is my settings:

```
!accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME --use_auth_token \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  **--instance_prompt="THE NAME I GAVE MY TOKEN ON THE HUGGING FACE SITE" \**
  --class_prompt="person" \
  --seed=1337 \
  --resolution=512 \
  --center_crop \
  --train_batch_size=1 \
  --mixed_precision="no" \
  --use_8_bit_adam \
  --gradient_accumulation_steps=1 \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=12 \
  --sample_batch_size=4 \
  --max_train_steps=900
```

### Logs

```shell
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
usage: train_dreambooth.py [-h] --pretrained_model_name_or_path
                           PRETRAINED_MODEL_NAME_OR_PATH
                           [--tokenizer_name TOKENIZER_NAME]
                           --instance_data_dir INSTANCE_DATA_DIR
                           [--class_data_dir CLASS_DATA_DIR]
                           [--instance_prompt INSTANCE_PROMPT]
                           [--class_prompt CLASS_PROMPT]
                           [--with_prior_preservation]
                           [--prior_loss_weight PRIOR_LOSS_WEIGHT]
                           [--num_class_images NUM_CLASS_IMAGES]
                           [--output_dir OUTPUT_DIR] [--seed SEED]
                           [--resolution RESOLUTION] [--center_crop]
                           [--train_batch_size TRAIN_BATCH_SIZE]
                           [--sample_batch_size SAMPLE_BATCH_SIZE]
                           [--num_train_epochs NUM_TRAIN_EPOCHS]
                           [--max_train_steps MAX_TRAIN_STEPS]
                           [--gradient_accumulation_steps GRADIENT_ACCUMULATION_STEPS]
                           [--gradient_checkpointing]
                           [--learning_rate LEARNING_RATE] [--scale_lr]
                           [--lr_scheduler LR_SCHEDULER]
                           [--lr_warmup_steps LR_WARMUP_STEPS]
                           [--use_8bit_adam] [--adam_beta1 ADAM_BETA1]
                           [--adam_beta2 ADAM_BETA2]
                           [--adam_weight_decay ADAM_WEIGHT_DECAY]
                           [--adam_epsilon ADAM_EPSILON]
                           [--max_grad_norm MAX_GRAD_NORM] [--push_to_hub]
                           [--use_auth_token] [--hub_token HUB_TOKEN]
                           [--hub_model_id HUB_MODEL_ID]
                           [--logging_dir LOGGING_DIR]
                           [--log_interval LOG_INTERVAL]
                           [--mixed_precision {no,fp16,bf16}]
                           [--not_cache_latents] [--local_rank LOCAL_RANK]
train_dreambooth.py: error: unrecognized arguments: --use_8_bit_adam
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/data/SteveInput', '--class_data_dir=/content/data/person', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/SteveOutput', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=nut', '--class_prompt=person', '--seed=1337', '--resolution=512', '--center_crop', '--train_batch_size=2', '--mixed_precision=no', '--use_8_bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=12', '--sample_batch_size=4', '--max_train_steps=900']' returned non-zero exit status 2.
```

### Additional Info
If I ignore it then I get another issue further on that states:

```
---------------------------------------------------------------------------
OSError Traceback (most recent call last)
in
6 model_path = OUTPUT_DIR # If you want to use previously trained model saved in gdrive, replace this with the full path of model in gdrive
7
----> 8 pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16).to("cuda")
9 g_cuda = None

1 frames
[/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
215 else:
216 raise EnvironmentError(
--> 217 f"Error no file named {cls.config_name} found in directory {pretrained_model_name_or_path}."
218 )
219 else:

OSError: Error no file named model_index.json found in directory /content/drive/MyDrive/stable_diffusion_weights/SteveOutput.
```

### System Info

Google Colab: https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb

**Comment by SingingTurnip** [comment]
If I ignore it then I get another issue further on that states:

`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
[<ipython-input-14-f97362b591c4>](https://localhost:8080/#) in <module>
      6 model_path = OUTPUT_DIR            # If you want to use previously trained model saved in gdrive, replace this with the full path of model in gdrive
      7 
----> 8 pipe = StableDiffusionPipeline.from_pretrained(model_path, torch_dtype=torch.float16).to("cuda")
      9 g_cuda = None

1 frames
[/usr/local/lib/python3.7/dist-packages/diffusers/configuration_utils.py](https://localhost:8080/#) in get_config_dict(cls, pretrained_model_name_or_path, **kwargs)
    215             else:
    216                 raise EnvironmentError(
--> 217                     f"Error no file named {cls.config_name} found in directory {pretrained_model_name_or_path}."
    218                 )
    219         else:

OSError: Error no file named model_index.json found in directory /content/drive/MyDrive/stable_diffusion_weights/SteveOutput.`

**Comment by ShivamShrirao** [comment]
It's `--use_8bit_adam` not `--use_8_bit_adam`.
