### ISSUE TITLE
Using [filewords] in 

### ISSUE THREAD

**Issue by plaidpants** [ShivamShrirao/diffusers#140]
### Describe the bug

trying to use file words in separate text files for each image results in an error, am I setting it up wrong or is this something that is just not supported with this colab

concepts_list = [
    {
        "instance_prompt":      "[filewords]",
        "class_prompt":         "a illustration in a style",
        "instance_data_dir":    "/content/data/gotothemoon",
        "class_data_dir":       "/content/data/illustration"
    },
]

### Reproduction

add a text file in the data directory that matches an image filename and use the [filewords] keyword in the instance prompt

### Logs

```shell
Traceback (most recent call last):
  File "train_dreambooth.py", line 822, in <module>
    main(args)
  File "train_dreambooth.py", line 613, in main
    for batch in tqdm(train_dataloader, desc="Caching latents"):
  File "/usr/local/lib/python3.7/dist-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train_dreambooth.py", line 323, in __getitem__
    instance_image = Image.open(instance_path)
  File "/usr/local/lib/python3.7/dist-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: **cannot identify image file** '/content/data/gotothemoon/00008-0-1959YouWillGoToTheMoon11.txt'
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=', '--revision=fp16', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=260', '--sample_batch_size=4', '--max_train_steps=4000', '--save_interval=10000', "--save_sample_prompt=a children's book illustration in the style of gotothemoon", '--concepts_list=concepts_list.json']' returned non-zero exit status 1.
```

### System Info

Tesla T4, 15109 MiB, 15109 MiB on google colab

**Comment by wcarletsdrive** [comment]
Yeah I was wondering if this repo allows us to use filewords/captions on our images and in the bat/shell file so we can have more customization with separating pictures within an overall concept. Would love to know how to do this as well

**Comment by Elevory** [comment]
I don't see anything in `train_dreambooth.py` that would suggest this feature exists. The term "filewords" does not appear in the script.

Would be a nice addition, although I remember hearing from folks on Discord that the careful labeling of input images may not have a positive effect on Dreambooth training.

**Comment by ansonkao** [comment]
`[filewords]` is implemented in the "Automatic1111 extension" fork for this repo:
https://github.com/d8ahazard/sd_dreambooth_extension
