### ISSUE TITLE
Attempting to train using the DreamBooth_Stable_Diffusion.ipynb now results in out of memory errors... and more...

### ISSUE THREAD

**Issue by TheMundaneDave** [ShivamShrirao/diffusers#146]
### Describe the bug

I just tried training a sd1.5 model using the notebook. When tryin to run the "!accelerate launch train_dreambooth.py" cell two things happened.
First a notice appeared before caching latents that made me think there were probably some changes going on. At the beginning of training the app just crashed due to CUDA not having enough memory (Runtime is using the standard Tesla T4, 15109 MiB, 15109 MiB)
I could try upping the runtime values but I figured things seem to be in a state of flux and to just report my problems. Full output in logs section:
ETA: I actually tried running it again in colab with a beefier GPU. That worked for a bit but it died suddenly after 1003 Steps of training. Error listed in logs under ERROR 2

### Logs

```shell
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
/usr/local/lib/python3.7/dist-packages/diffusers/utils/deprecation_utils.py:35: FutureWarning: It is deprecated to pass a pretrained model name or path to `from_config`.If you were trying to load a scheduler, please use <class 'diffusers.schedulers.scheduling_ddpm.DDPMScheduler'>.from_pretrained(...) instead. Otherwise, please make sure to pass a configuration dictionary instead. This functionality will be removed in v1.0.0.
  warnings.warn(warning + message, FutureWarning)
Caching latents: 100% 500/500 [01:43<00:00,  4.84it/s]
Steps:   0% 0/5000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 822, in <module>
    main(args)
  File "train_dreambooth.py", line 786, in main
    accelerator.backward(loss)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/accelerator.py", line 882, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/_tensor.py", line 396, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 175, in backward
    allow_unreachable=True, accumulate_grad=True)  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 4.99 GiB (GPU 0; 14.76 GiB total capacity; 7.20 GiB already allocated; 4.99 GiB free; 8.44 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0% 0/5000 [00:07<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/project010', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=500', '--sample_batch_size=4', '--max_train_steps=5000', '--save_interval=500', '--save_sample_prompt=photo of a woman', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.
[ ]
---ERROR 2---
Steps:  20% 1003/5000 [10:43<4:59:05,  4.49s/it, loss=0.285, lr=1e-6]Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/drive/MyDrive/stable_diffusion_weights/project010', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=500', '--sample_batch_size=4', '--max_train_steps=5000', '--save_interval=500', '--save_sample_prompt=photo of a woman', '--concepts_list=concepts_list.json']' died with <Signals.SIGABRT: 6>.
```

### System Info

running notebook in colab

**Comment by ShivamShrirao** [comment]
Can u try by disabling latents cache with `--not_cache_latents` ?

**Comment by TheMundaneDave** [comment]
I'll give it a try. Shouldn't I cache latents though? I mean, for the quality of training. I'll report back

**Comment by TheMundaneDave** [comment]
Well, it's slow (45 minutes and only 1500 steps) but seems to be functioning...

**Comment by ShivamShrirao** [comment]
Yeah it be will slower but will use less memory if u have lot of classes or instance images.
