### ISSUE TITLE
List Index out of range on grid generation

### ISSUE THREAD

**Issue by VbGomes** [ShivamShrirao/diffusers#153]
### Describe the bug

When trying to run the block to generate a grid of preview images from the last saved weights, I get the following error message:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-18-13577182bc6b>](https://localhost:8080/#) in <module>
      8 
      9 row = len(folders)
---> 10 col = range(len(os.listdir(os.path.join(weights_folder, folders[0], "samples"))))
     11 scale = 4
     12 fig, axes = plt.subplots(row, col, figsize=(col*scale, row*scale), gridspec_kw={'hspace': 0, 'wspace': 0})

IndexError: list index out of range
---------------------------------------------------------------------------

I've tried many solutions with whatever poor knowledge and research I could gather but to no avail.
Every other step before this one has been sucessful, with a minor side note for this message on `!accelerate launch train_dreambooth.py \` block:

---------------------------------------------------------------------------
The following values were not passed to `accelerate launch` and had defaults used instead:
	`--num_processes` was set to a value of `1`
	`--num_machines` was set to a value of `1`
	`--mixed_precision` was set to a value of `'no'`
	`--num_cpu_threads_per_process` was set to `1` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py", line 239, in hf_raise_for_status
    response.raise_for_status()
--->  **File "/usr/local/lib/python3.8/dist-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/fp16/model_index.json**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 324, in load_config
    config_file = hf_hub_download(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1067, in hf_hub_download
    metadata = get_hf_file_metadata(
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_validators.py", line 124, in _inner_fn
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/file_download.py", line 1376, in get_hf_file_metadata
    hf_raise_for_status(r)
--->  **File "/usr/local/lib/python3.8/dist-packages/huggingface_hub/utils/_errors.py", line 268, in hf_raise_for_status
    raise RepositoryNotFoundError(message, response) from e
huggingface_hub.utils._errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-6389207b-229e3c9c5fe60d5a54834a49)**

**Repository Not Found for url: https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/fp16/model_index.json.
Please make sure you specified the correct `repo_id` and `repo_type`.
If the repo is private, make sure you are authenticated.**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "train_dreambooth.py", line 822, in <module>
    main(args)
  File "train_dreambooth.py", line 448, in main
    pipeline = StableDiffusionPipeline.from_pretrained(
  File "/usr/local/lib/python3.8/dist-packages/diffusers/pipeline_utils.py", line 447, in from_pretrained
    config_dict = cls.load_config(
--->  **File "/usr/local/lib/python3.8/dist-packages/diffusers/configuration_utils.py", line 339, in load_config
    raise EnvironmentError(
OSError: runwayml/stable-diffusion-v1-5 is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login`.**

Traceback (most recent call last):

  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
--->  **File "/usr/local/lib/python3.8/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/stable_diffusion_weights/zwx', '--revision=fp16', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=4', '--max_train_steps=1600', '--save_interval=10000', '--save_sample_prompt=vbgomes', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.**
---------------------------------------------------------------------------

I've added arrows to where I think there could be some issue with the repository, but as stated before, my knowledge is rather limited.

Any fixes?

### System Info

- `diffusers` version: 0.9.0
- Platform: Linux-5.10.133+-x86_64-with-glibc2.27
- Python version: 3.8.15
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.24.0
- Using GPU in script?: Tesla T4, 15109 MiB, 15109 MiB
- Using distributed or parallel set-up in script?: Parallel

**Comment by deveshruttala** [comment]
i am also receiving this issue
