### ISSUE TITLE
UnboundLocalError: local variable 'num_processes' referenced before assignment

### ISSUE THREAD

**Issue by ZeroCool22** [ShivamShrirao/diffusers#16]
### Describe the bug

```
Do you wish to use FP16 or BF16 (mixed precision)? [NO/fp16/bf16]: fp16
Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/config/__init__.py", line 64, in config_command
    config = get_user_input()
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/config/__init__.py", line 37, in get_user_input
    config = get_cluster_input()
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/config/cluster.py", line 334, in get_cluster_input
    num_processes=num_processes,
UnboundLocalError: local variable 'num_processes' referenced before assignment
```

### System Info

- `diffusers` version: 0.3.0
- Platform: Windows-10-10.0.19044-SP0
- Python version: 3.10.6
- PyTorch version (GPU?): 1.12.1+cu113 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.20.0
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by nerdyrodent** [comment]
Try ```pip install accelerate==0.12.0```

**Comment by ZeroCool22** [comment]
> Try `pip install accelerate==0.12.0`

Thx, it's already satisfied:


```
(diffusers) zerocool@DESKTOP-IFR8E96:~/github/diffusers/examples/dreambooth$ pip install accelerate==0.12.0
Requirement already satisfied: accelerate==0.12.0 in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (0.12.0)
Requirement already satisfied: packaging>=20.0 in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from accelerate==0.12.0) (21.3)
Requirement already satisfied: torch>=1.4.0 in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from accelerate==0.12.0) (1.12.1+cu116)
Requirement already satisfied: pyyaml in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from accelerate==0.12.0) (6.0)
Requirement already satisfied: numpy>=1.17 in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from accelerate==0.12.0) (1.23.3)
Requirement already satisfied: psutil in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from accelerate==0.12.0) (5.9.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from packaging>=20.0->accelerate==0.12.0) (3.0.9)
Requirement already satisfied: typing-extensions in /home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages (from torch>=1.4.0->accelerate==0.12.0) (4.3.0)
(diffusers) zerocool@DESKTOP-IFR8E96:~/github/diffusers/examples/dreambooth$
```
