### ISSUE TITLE
Still get fp32 wrapper error

### ISSUE THREAD

**Issue by G-force78** [ShivamShrirao/diffusers#182]
### Describe the bug

Steps:  33% 500/1500 [09:06<17:56,  1.08s/it, loss=0.286, lr=1e-6]Traceback (most recent call last):
```
  File "train_dreambooth.py", line 822, in <module>
    main(args)
  File "train_dreambooth.py", line 805, in main
    save_weights(global_step)
  File "train_dreambooth.py", line 682, in save_weights
    text_enc_model = accelerator.unwrap_model(text_encoder, keep_fp32_wrapper=True)
```

### Reproduction

Train and save part way. 

### System Info

- `diffusers` version: 0.9.0
- Platform: Linux-5.10.147+-x86_64-with-glibc2.27
- Python version: 3.8.16
- PyTorch version (GPU?): 1.13.0+cu116 (True)
- Huggingface_hub version: 0.11.1
- Transformers version: 4.25.1
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by OMGhozlan** [comment]
Can confirm that as per @ShivamShrirao's response in #180, you just need to update accelerate.
Change `%pip install -q accelerate==0.12.0 transformers ftfy bitsandbytes gradio natsort`
to `%pip install -q accelerate transformers ftfy bitsandbytes gradio natsort`

**Comment by 2blackbar** [comment]
so what should it be ? bitsandbytes or bitsandbytes 35? im getting crap results still , half hour ago

**Comment by G-force78** [comment]
Not sure if related but now get this error
RuntimeError: Detected that PyTorch and torchvision were compiled with different CUDA versions. PyTorch has CUDA Version=11.7 and torchvision has CUDA Version=11.6. Please reinstall the torchvision that matches your PyTorch install.

**Comment by ShivamShrirao** [comment]
@G-force78 fixed in 8b1472ffd0c8e0144f9db797e545eb908a1831b9
