### ISSUE TITLE
Still returned non-zero exit status 1.

### ISSUE THREAD

**Issue by ZeroCool22** [ShivamShrirao/diffusers#23]
### Describe the bug

```
(diffusers) zerocool@DESKTOP-IFR8E96:~/github/diffusers/examples/dreambooth$ ./my_training.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
WARNING:root:Blocksparse is not available: the current GPU does not expose Tensor cores
The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.
Moving 0 files to the new cache system
0it [00:00, ?it/s]
Caching latents:   9%|██████                                                             | 4/44 [00:02<00:23,  1.73it/s]
Traceback (most recent call last):
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 637, in <module>
    main()
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 492, in main
    for batch in tqdm(train_dataloader, desc="Caching latents"):
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 261, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/home/zerocool/github/diffusers/examples/dreambooth/training/is-that-what-you-think-photo-u2.jpg:Zone.Identifier'
Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zerocool/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--output_dir=my_model', '--instance_prompt=beaninstance', '--class_prompt=guy', '--resolution=512', '--train_batch_size=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--max_train_steps=1000']' returned non-zero exit status 1.
(diffusers) zerocool@DESKTOP-IFR8E96:~/github/diffusers/examples/dreambooth$
```

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.22.2
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by ShivamShrirao** [comment]
`/home/zerocool/github/diffusers/examples/dreambooth/training/is-that-what-you-think-photo-u2.jpg:Zone.Identifier`

Check this file name, fix its extension.

**Comment by ZeroCool22** [comment]
> `/home/zerocool/github/diffusers/examples/dreambooth/training/is-that-what-you-think-photo-u2.jpg:Zone.Identifier`
> 
> Check this file name, fix its extension.

Yeah, i sorted that out but i still have this problem: https://github.com/ShivamShrirao/diffusers/issues/20#issuecomment-1270708603
