### ISSUE TITLE
does it work on windows? winerror123 directory syntax incorrect

### ISSUE THREAD

**Issue by andreae293** [ShivamShrirao/diffusers#24]
### Describe the bug

im trying to make dreambooth work on windows, but with no luck
the following error appears
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"CompVis\\stable-diffusion-v1-4"'

full traceback:
```
launch.bat
accelerate launch train_dreambooth.py --pretrained_model_name_or_path="CompVis/stable-diffusion-v1-4" --use_auth_token --instance_data_dir="training_data\dog"   --class_data_dir="regularization"   --output_dir="outputs\models\dog"   --with_prior_preservation --prior_loss_weight=1.0   --instance_prompt="A sks dog"   --class_prompt="A dog"   --seed=3434554   --resolution=512   --center_crop   --train_batch_size=1      --use_8bit_adam   --gradient_accumulation_steps=1   --learning_rate=5e-6   --lr_scheduler="constant"   --lr_warmup_steps=0   --num_class_images=12 --sample_batch_size=4   --max_train_steps=800

The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: Could not find module 'C:\Users\andre\anaconda3\envs\ldm\Lib\site-packages\torchvision\image.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
  warn(f"Failed to load image Python extension: {e}")

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {WindowsPath('C')}
  warn(
C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py:86: UserWarning: C:\Users\andre\anaconda3\envs\ldm did not contain libcudart.so as expected! Searching further paths...
  warn(
Traceback (most recent call last):
  File "train_dreambooth.py", line 658, in <module>
    main()
  File "train_dreambooth.py", line 446, in main
    import bitsandbytes as bnb
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from .autograd._functions import (
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\autograd\_functions.py", line 5, in <module>
    import bitsandbytes.functional as F
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\functional.py", line 13, in <module>
    from .cextension import COMPILED_WITH_CUDA, lib
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cextension.py", line 41, in <module>
    lib = CUDALibrary_Singleton.get_instance().lib
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cextension.py", line 37, in get_instance
    cls._instance.initialize()
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cextension.py", line 15, in initialize
    binary_name = evaluate_cuda_setup()
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\main.py", line 123, in evaluate_cuda_setup
    cudart_path = determine_cuda_runtime_lib_path()
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py", line 110, in determine_cuda_runtime_lib_path
    cuda_runtime_libs.update(find_cuda_lib_in(value))
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py", line 46, in find_cuda_lib_in
    resolve_paths_list(paths_list_candidate)
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py", line 41, in resolve_paths_list
    return remove_non_existent_dirs(extract_candidate_paths(paths_list_candidate))
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py", line 15, in remove_non_existent_dirs
    non_existent_directories: Set[Path] = {
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\bitsandbytes\cuda_setup\paths.py", line 16, in <setcomp>
    path for path in candidate_paths if not path.exists()
  File "C:\Users\andre\anaconda3\envs\ldm\lib\pathlib.py", line 1388, in exists
    self.stat()
  File "C:\Users\andre\anaconda3\envs\ldm\lib\pathlib.py", line 1194, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '"CompVis\\stable-diffusion-v1-4"'
Traceback (most recent call last):
  File "C:\Users\andre\anaconda3\envs\ldm\Scripts\accelerate-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\accelerate_cli.py", line 43, in main
    args.func(args)
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\launch.py", line 837, in launch_command
    simple_launcher(args)
  File "C:\Users\andre\anaconda3\envs\ldm\lib\site-packages\accelerate\commands\launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\andre\\anaconda3\\envs\\ldm\\python.exe', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=training_data\\dog', '--class_data_dir=regularization', '--output_dir=outputs\\models\\dog', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=A sks dog', '--class_prompt=A dog', '--seed=3434554', '--resolution=512', '--center_crop', '--train_batch_size=1', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=12', '--sample_batch_size=4', '--max_train_steps=800']' returned non-zero exit status 1.
```

### System Info

Windows

**Comment by mhnoni** [comment]
Did you had any luck to run this with windows?

**Comment by andreae293** [comment]
no, at the end i used wsl to run it as explained there
https://www.youtube.com/watch?v=w6PTviOCYQY

**Comment by mhnoni** [comment]
> no, at the end i used wsl to run it as explained there https://www.youtube.com/watch?v=w6PTviOCYQY

I see, thanks!
