### ISSUE TITLE
Please could somebody help

### ISSUE THREAD

**Issue by HAV3RGAN** [ShivamShrirao/diffusers#25]
Hey guys,  I'm not quite sure what's going on here however I followed nerdy rodents [video](https://www.youtube.com/watch?v=w6PTviOCYQY) to get this working on ubuntu (in windows) however I am getting this error. have I done something wrong? Any help/advice would be welcome as I'm not the best at this kind of thing. thank you :)

`The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `12` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:86: UserWarning: /home/bobross/anaconda3/envs/diffusers did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:98: UserWarning: /usr/lib/wsl/lib: did not contain libcudart.so as expected! Searching further paths...
  warn(
/home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/cuda_setup/paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('CompVis/stable-diffusion-v1-4')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Traceback (most recent call last):
  File "/home/bobross/github/diffusers/examples/dreambooth/train_dreambooth.py", line 637, in <module>
    main()
  File "/home/bobross/github/diffusers/examples/dreambooth/train_dreambooth.py", line 450, in main
    train_dataset = DreamBoothDataset(
  File "/home/bobross/github/diffusers/examples/dreambooth/train_dreambooth.py", line 230, in __init__
    raise ValueError("Instance images root doesn't exists.")
ValueError: Instance images root doesn't exists.
Traceback (most recent call last):
  File "/home/bobross/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/bobross/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/bobross/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=path-to-instance-images', '--output_dir=path-to-save-model', '--instance_prompt=a photo of sks dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=2', '--gradient_checkpointing', '--use_8bit_adam', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--max_train_steps=400']' returned non-zero exit status 1.`

I have added my 512x512 images into the "training folder" but that's it.

**Comment by ZeroCool22** [comment]
**ValueError("Instance images root doesn't exists.")**

**Comment by HAV3RGAN** [comment]
> 

what does that mean mate ? how could i fix that please?

**Comment by econDS** [comment]
--instance_data_dir="training folder" \

**Comment by HAV3RGAN** [comment]
econDS, thank you soo much that fixed it. i do have one more question. when i use the online collab version i can select what the class name is and my prompt however in mr rodents "no_pres.sh" it doesn't have that soo how do i know what to promp to tell SD. i have finished the training and more confused than earlier lol. Soo sorry for being a newbie.
