### ISSUE TITLE
NotImplementedError when running training on WSL Ubuntu

### ISSUE THREAD

**Issue by masonj19** [ShivamShrirao/diffusers#26]
Hello! I am trying to get diffusers dreambooth running with WSL Ubuntu on my 3090ti computer. I have been following this [ youtube video](https://www.youtube.com/watch?v=w6PTviOCYQY) by nerdy rodent. However when I run the training I receive this error:

<details>
  <summary> --- Full Error Spoiler --- </summary>
  
```
(diffusers) user@DESKTOP-3PGA1RN:~/github/diffusers/examples/dreambooth$ ./my_training.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `8` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
Caching latents: 100%|████████████████████████████████████████████████████████████████| 200/200 [59:25<00:00, 17.83s/it]
Steps:   0%|                                                                                    | 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/user/github/diffusers/examples/dreambooth/train_dreambooth.py", line 637, in <module>
    main()
  File "/home/user/github/diffusers/examples/dreambooth/train_dreambooth.py", line 582, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/models/unet_2d_condition.py", line 283, in forward
    sample, res_samples = downsample_block(
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/models/unet_blocks.py", line 565, in forward
    hidden_states = attn(hidden_states, context=encoder_hidden_states)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/models/attention.py", line 154, in forward
    hidden_states = block(hidden_states, context=context)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/models/attention.py", line 203, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/diffusers/models/attention.py", line 276, in forward
    hidden_states = xformers.ops.memory_efficient_attention(query, key, value)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/xformers/ops.py", line 568, in memory_efficient_attention
    op = AttentionOpDispatch.from_arguments(
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/xformers/ops.py", line 531, in op
    raise NotImplementedError(f"No operator found for this attention: {self}")
NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096)
Steps:   0%|                                                                                    | 0/800 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/user/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/user/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--class_data_dir=classes', '--output_dir=output_models', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--gradient_accumulation_steps=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800']' returned non-zero exit status 1.
(diffusers) user@DESKTOP-3PGA1RN:~/github/diffusers/examples/dreambooth$
```
  
</details>

I have 16 images of my subject in `./training` and 200 images of the subject class in `./classes`.

It seems to me that maybe it is trying to run on the cpu but I don't really know for sure.
`NotImplementedError: No operator found for this attention: AttentionOpDispatch(dtype=torch.float32, device=device(type='cpu'), k=40, has_dropout=False, attn_bias_type=<class 'NoneType'>, kv_len=4096, q_len=4096)`

If anyone has any insight into this error I would very much appreciate your wisdom.

**Comment by ShivamShrirao** [comment]
Yup it's cause it is trying to run on CPU, your GPU isn't being detected in WSL.

**Comment by masonj19** [comment]
Thank you so much for your comment! After hours of troubleshooting, I finally figured out the specific problem. In case anyone else is running into this error, make sure your WSL linux distro is version 2 (WSL2) and not regular WSL or it does not work.

**Comment by ChinaArvin** [comment]
NotImplementedError: Could not run 'xformers::efficient_attention_forward_generic' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions.

Hi, Could you please help to analyze this mistake

**Comment by kyuumeitai** [comment]
I had the same problem, I was using the Nerdy Rodent guide ( https://pastebin.com/uE1WcSxD ). The specific error was:

`NotImplementedError: Could not run 'xformers::efficient_attention_forward_generic' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'xformers::efficient_attention_forward_generic' is only available for these backends: [UNKNOWN_TENSOR_TYPE_ID, QuantizedXPU, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseCPU, SparseCUDA, SparseHIP, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, SparseVE, UNKNOWN_TENSOR_TYPE_ID, NestedTensorCUDA, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID, UNKNOWN_TENSOR_TYPE_ID].`

I fixed by installing another xformers version as seen on [this comment ](url)https://github.com/ShivamShrirao/diffusers/issues/6#issuecomment-1266053624

`pip install git+https://github.com/facebookresearch/xformers@51dd119#egg=xformers`
