### ISSUE TITLE
Error in the Dreambooth

### ISSUE THREAD

**Issue by greendesertsnow** [ShivamShrirao/diffusers#4]
### Describe the bug

It it happens when you start the training. There's not a lot of information on why. 

### Reproduction

Regular flow of the colab file produces this

### Logs

```shell
Traceback (most recent call last):
  File "train_dreambooth.py", line 658, in <module>
    main()
  File "train_dreambooth.py", line 510, in main
    for batch in tqdm(train_dataloader, desc="Caching latents"):
  File "/opt/conda/lib/python3.7/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 652, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 692, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "train_dreambooth.py", line 270, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
ZeroDivisionError: integer division or modulo by zero
Traceback (most recent call last):
  File "/opt/conda/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/opt/conda/lib/python3.7/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/content/data/tomellis', '--class_data_dir=/content/data/guy', '--output_dir=/content/stable_diffusion_weights/tomellis', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=tomellis', '--class_prompt=tomellis guy']' returned non-zero exit status 1.
```

### System Info

 RTX 3090
(Colab A100 too produces an other error in the same step.)

**Comment by rSh4d0w** [comment]
Training fails at " File "train_dreambooth.py", line 270, in __getitem__
    instance_image = Image.open(self.instance_images_path[index % self.num_instance_images])
ZeroDivisionError: integer division or modulo by zero" So you either didn't specifiy the correct folder with your training images, or your folder is empty.
Either way, you can't train without images to train on.

**Comment by ShivamShrirao** [comment]
Yup, as @rSh4d0w said, your training images folder is empty.
