### ISSUE TITLE
cuda out of memory with gtx 1070 vram 8GB 64GBRAM using deepspeed

### ISSUE THREAD

**Issue by mhnoni** [ShivamShrirao/diffusers#61]
### Describe the bug

Hi, using deepspeed I can see my gpu is reaching > 7GB and ram > 24GB then I get cuda out of memory. below the fall log.

(diffusers) n@DESKTOP-0J7ELM7:~/github/diffusers/examples/dreambooth$ ./my_training.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `16` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
[2022-10-24 02:26:57,607] [WARNING] [runner.py:178:fetch_hostfile] Unable to find hostfile, will proceed with training with local resources only.
[2022-10-24 02:26:57,797] [INFO] [runner.py:504:main] cmd = /home/n/anaconda3/envs/diffusers/bin/python -u -m deepspeed.launcher.launch --world_info=eyJsb2NhbGhvc3QiOiBbMF19 --master_addr=127.0.0.1 --master_port=29500 --no_local_rank train_dreambooth.py --pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4 --instance_data_dir=training --class_data_dir=path-to-class-images --output_dir=path-to-save-model --instance_prompt=a photo of sks dog --class_prompt=a photo of dog --resolution=512 --train_batch_size=1 --sample_batch_size=1 --gradient_accumulation_steps=1 --gradient_checkpointing --learning_rate=5e-6 --lr_scheduler=constant --lr_warmup_steps=0 --num_class_images=200 --max_train_steps=800 --mixed_precision=fp16
[2022-10-24 02:26:58,802] [INFO] [launch.py:136:main] WORLD INFO DICT: {'localhost': [0]}
[2022-10-24 02:26:58,802] [INFO] [launch.py:142:main] nnodes=1, num_local_procs=1, node_rank=0
[2022-10-24 02:26:58,802] [INFO] [launch.py:155:main] global_rank_mapping=defaultdict(<class 'list'>, {'localhost': [0]})
[2022-10-24 02:26:58,802] [INFO] [launch.py:156:main] dist_world_size=1
[2022-10-24 02:26:58,802] [INFO] [launch.py:158:main] Setting CUDA_VISIBLE_DEVICES=0
[2022-10-24 02:27:00,464] [INFO] [comm.py:633:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
Caching latents: 100%|████████████████████████████████████████████████████████████████████| 4/4 [00:02<00:00,  1.64it/s]
[2022-10-24 02:27:18,155] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed info: version=0.7.3, git-hash=unknown, git-branch=unknown
[2022-10-24 02:27:19,046] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Flops Profiler Enabled: False
[2022-10-24 02:27:19,047] [INFO] [logging.py:68:log_dist] [Rank 0] Removing param_group that has no 'params' in the client Optimizer
[2022-10-24 02:27:19,047] [INFO] [logging.py:68:log_dist] [Rank 0] Using client Optimizer as basic optimizer
[2022-10-24 02:27:19,095] [INFO] [logging.py:68:log_dist] [Rank 0] DeepSpeed Basic Optimizer = {basic_optimizer.__class__.__name__}
[2022-10-24 02:27:19,095] [INFO] [utils.py:52:is_zero_supported_optimizer] Checking ZeRO support for optimizer=AdamW type=<class 'torch.optim.adamw.AdamW'>
[2022-10-24 02:27:19,095] [INFO] [logging.py:68:log_dist] [Rank 0] Creating fp16 ZeRO stage 3 optimizer
[2022-10-24 02:27:19,132] [INFO] [utils.py:827:see_memory_usage] Stage 3 initialize beginning
[2022-10-24 02:27:19,133] [INFO] [utils.py:828:see_memory_usage] MA 1.62 GB         Max_MA 1.62 GB         CA 1.67 GB         Max_CA 2 GB
[2022-10-24 02:27:19,133] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 4.19 GB, percent = 8.4%
[2022-10-24 02:27:19,136] [INFO] [stage3.py:114:__init__] Reduce bucket size 500000000
[2022-10-24 02:27:19,136] [INFO] [stage3.py:115:__init__] Prefetch bucket size 50000000
Using /home/n/.cache/torch_extensions/py39_cu116 as PyTorch extensions root...
Emitting ninja build file /home/n/.cache/torch_extensions/py39_cu116/utils/build.ninja...
Building extension module utils...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module utils...
Time to load utils op: 0.12457728385925293 seconds
[2022-10-24 02:27:19,565] [INFO] [utils.py:827:see_memory_usage] DeepSpeedZeRoOffload initialize [begin]
[2022-10-24 02:27:19,566] [INFO] [utils.py:828:see_memory_usage] MA 1.62 GB         Max_MA 1.62 GB         CA 1.67 GB         Max_CA 2 GB
[2022-10-24 02:27:19,566] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 4.21 GB, percent = 8.4%
Parameter Offload: Total persistent parameters: 466884 in 406 params
[2022-10-24 02:27:20,081] [INFO] [utils.py:827:see_memory_usage] DeepSpeedZeRoOffload initialize [end]
[2022-10-24 02:27:20,082] [INFO] [utils.py:828:see_memory_usage] MA 0.0 GB         Max_MA 1.62 GB         CA 1.67 GB         Max_CA 2 GB
[2022-10-24 02:27:20,082] [INFO] [utils.py:836:see_memory_usage] CPU Virtual Memory:  used = 5.12 GB, percent = 10.2%
Traceback (most recent call last):
  File "/home/n/github/diffusers/examples/dreambooth/train_dreambooth.py", line 695, in <module>
    main()
  File "/home/n/github/diffusers/examples/dreambooth/train_dreambooth.py", line 560, in main
    unet, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/accelerator.py", line 619, in prepare
    result = self._prepare_deepspeed(*args)
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/accelerator.py", line 805, in _prepare_deepspeed
    engine, optimizer, _, lr_scheduler = deepspeed.initialize(**kwargs)
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/__init__.py", line 124, in initialize
    engine = DeepSpeedEngine(args=args,
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 320, in __init__
    self._configure_optimizer(optimizer, model_parameters)
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1144, in _configure_optimizer
    self.optimizer = self._configure_zero_optimizer(basic_optimizer)
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 1446, in _configure_zero_optimizer
    optimizer = DeepSpeedZeroOptimizer_Stage3(
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 256, in __init__
    self._create_fp16_partitions_with_defragmentation()
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 607, in _create_fp16_partitions_with_defragmentation
    self._create_param_groups_fp16_flat_cpu_memory()
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/deepspeed/runtime/zero/stage3.py", line 543, in _create_param_groups_fp16_flat_cpu_memory
    torch.empty(int(flat_buffer_size),
**RuntimeError: CUDA error: out of memory**
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
[2022-10-24 02:27:21,828] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 599
[2022-10-24 02:27:21,829] [ERROR] [launch.py:292:sigkill_handler] ['/home/n/anaconda3/envs/diffusers/bin/python', '-u', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--class_data_dir=path-to-class-images', '--output_dir=path-to-save-model', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--sample_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800', '--mixed_precision=fp16'] exits with return code = 1
Traceback (most recent call last):
  File "/home/n/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 827, in launch_command
    deepspeed_launcher(args)
  File "/home/n/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 540, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--num_gpus', '1', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--instance_data_dir=training', '--class_data_dir=path-to-class-images', '--output_dir=path-to-save-model', '--instance_prompt=a photo of sks dog', '--class_prompt=a photo of dog', '--resolution=512', '--train_batch_size=1', '--sample_batch_size=1', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=200', '--max_train_steps=800', '--mixed_precision=fp16']' returned non-zero exit status 1.
(diffusers) n@DESKTOP-0J7ELM7:~/github/diffusers/examples/dreambooth$

### System Info

win 10 pro version 22H2 
5950x
64GB ram
gtx 1070 8GB
wsl2

**Comment by WakizashiYoshikawa** [comment]
Confirming the same results Windows 10 22H2, WSL2, RTX 2060 Super 8GB

**Comment by 78Alpha** [comment]
Same here with 21H1, WSL2, RTX 3070 8GB

**Comment by 78Alpha** [comment]
And can confirm again with Windows 11 22H2, WSL2, Ubuntu 18.04 - 22.04, RTX 3070 8 GB
