### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file. After last GIT PULL.

### ISSUE THREAD

**Issue by ZeroCool22** [ShivamShrirao/diffusers#67]
### Describe the bug

**Zone.Identifier'**

What this mean?

```
Caching latents:  33%|█████████████████████▍                                           | 33/100 [00:12<00:24,  2.69it/s]
Traceback (most recent call last):
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 750, in <module>
    main()
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 555, in main
    for batch in tqdm(train_dataloader, desc="Caching latents"):
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/tqdm/std.py", line 1195, in __iter__
    for obj in iterable:
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/zerocool/github/diffusers/examples/dreambooth/train_dreambooth.py", line 293, in __getitem__
    instance_image = Image.open(instance_path)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/PIL/Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '/home/zerocool/github/diffusers/examples/dreambooth/training/5.png:Zone.Identifier'
Traceback (most recent call last):
  File "/home/zerocool/anaconda3/envs/diffusers/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/home/zerocool/anaconda3/envs/diffusers/lib/python3.9/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/zerocool/anaconda3/envs/diffusers/bin/python', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--instance_data_dir=training', '--class_data_dir=classes', '--output_dir=my_model', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=Stn6', '--class_prompt=man', '--resolution=512', '--train_batch_size=1', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--gradient_accumulation_steps=4', '--gradient_checkpointing', '--use_8bit_adam', '--max_train_steps=3000']' returned non-zero exit status 1.
(diffusers) zerocool@DESKTOP-IFR8E96:~/github/diffusers/examples/dreambooth$
```

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31
- Python version: 3.9.13
- PyTorch version (GPU?): 1.12.1+cu116 (True)
- Huggingface_hub version: 0.10.0
- Transformers version: 4.22.2
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by ShivamShrirao** [comment]
Read the name of your image, it has some extra characters after the extension.


`/home/zerocool/github/diffusers/examples/dreambooth/training/5.png:Zone.Identifier`

**Comment by ZeroCool22** [comment]
> Read the name of your image, it has some extra characters after the extension.
> 
> `/home/zerocool/github/diffusers/examples/dreambooth/training/5.png:Zone.Identifier`

Yeah, i closed it because i see the cause was that image.
