### ISSUE TITLE
Bug: can no longer start with previously trained model (Repo id must be in the form 'repo_name' or 'namespace/repo_name)

### ISSUE THREAD

**Issue by jmp909** [ShivamShrirao/diffusers#68]
### Describe the bug

when adding a previously trained model as MODEL_DIR there is now an error from huggingface that it is not a repo

`MODEL_NAME=/content/drive/MyDrive/jmp909/sd/stable-diffusion-weights/jmp909_2600`

`Repo id must be in the form 'repo_name' or 'namespace/repo_name'`

### Reproduction

change `MODEL_NAME` to point to a previous model not the `runwayml` repo

### Logs

```shell
Traceback (most recent call last):
  File "train_dreambooth.py", line 750, in <module>
    main()
  File "train_dreambooth.py", line 456, in main
    tokenizer = CLIPTokenizer.from_pretrained(args.pretrained_model_name_or_path, subfolder="tokenizer", use_auth_token=True)
  File "/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py", line 1748, in from_pretrained
    _commit_hash=commit_hash,
  File "/usr/local/lib/python3.7/dist-packages/transformers/utils/hub.py", line 420, in cached_file
    local_files_only=local_files_only,
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/file_download.py", line 1022, in hf_hub_download
    cache_dir, repo_folder_name(repo_id=repo_id, repo_type=repo_type)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 92, in _inner_fn
    validate_repo_id(arg_value)
  File "/usr/local/lib/python3.7/dist-packages/huggingface_hub/utils/_validators.py", line 137, in validate_repo_id
    "Repo id must be in the form 'repo_name' or 'namespace/repo_name':"
huggingface_hub.utils._validators.HFValidationError: Repo id must be in the form 'repo_name' or 'namespace/repo_name': 
'/content/drive/MyDrive/jmp909/sd/stable-diffusion-weights/jmp909_2600'. Use `repo_type` argument if needed.
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
```

### System Info

(latest training colab as of 2022-10-24)

**Comment by jmp909** [comment]
@InB4DevOps latest version. the `repo_type` looks like is coming from the hugging face library rather than Shivam's code?

**Comment by ShivamShrirao** [comment]
I am unable to reproduce this, can u tell what are the contents of your model path ?

**Comment by jmp909** [comment]
@ShivamShrirao same as usual. it's the diffusers folder trained to 1000 steps from the original runwayml repo, then i repoint the MODEL_NAME back to that to resume later. it worked a few days ago

`MODEL_NAME = "jmp909/sd/stable_diffusion_weights/jmp909/1000"` (with /content/drive/MyDrive prepended on next step)

![image](https://user-images.githubusercontent.com/2184982/197868014-57193702-2ad3-4ca6-a69a-2b3ad3132d96.png)

**Comment by jmp909** [comment]
@ShivamShrirao  sorry my bad gdrive is not prepended to `MODEL_NAME`. it's not currently an option to specify they will be loaded from gdrive so my path was missing `/content/drive/MyDrive`

i can just add it, but it would be useful to allow people to resume in this way by adding an eg "load weights from gdrive" checkbox etc... well in fact all of my reusable data (images, weights, models) etc use my gdrive not the volatile colab memory

it doesn't specifically need fixing here therefore, so I'll close this.

**Comment by jmp909** [comment]
(just to note, it would be useful to check the path before training cell is started earlier when the setup cell is run though.. the error was slightly misleading)

thanks
