### ISSUE TITLE
RuntimeError: CUDA out of memory on PC with RTX3060

### ISSUE THREAD

**Issue by weicao0** [ShivamShrirao/diffusers#8]
### Describe the bug

1.I run the launch.sh on my PC with RTX3060 which has 12G VRAM, the error info listed below.
2.I try set "export PYTORCH_CUDA_ALLOC_CONF=max_split_size_mb:32" but not useful.

### Reproduction

1. here is my launch.sh. I hope someone can repoduce the process.
# cat launch.sh
export MODEL_NAME="CompVis/stable-diffusion-v1-4"
export INSTANCE_DIR="/workspace/develop/huggingface-diffusers/dreambooth/data/alvan"
export CLASS_DIR="/workspace/develop/huggingface-diffusers/dreambooth/data/dog"
export OUTPUT_DIR="/workspace/develop/huggingface-diffusers/dreambooth/models/dog2"

accelerate launch train_dreambooth.py \
  --pretrained_model_name_or_path=$MODEL_NAME --use_auth_token \
  --instance_data_dir=$INSTANCE_DIR \
  --class_data_dir=$CLASS_DIR \
  --output_dir=$OUTPUT_DIR \
  --with_prior_preservation --prior_loss_weight=1.0 \
  --instance_prompt="photo of sks dog" \
  --class_prompt="photo of a dog" \
  --seed=3434554 \
  --resolution=512 \
  --center_crop \
  --train_batch_size=1 \
  --mixed_precision="fp16" \
  --use_8bit_adam \
  --gradient_accumulation_steps=1 --gradient_checkpointing \
  --learning_rate=5e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --num_class_images=12 \
  --sample_batch_size=4 \
  --max_train_steps=800

### Logs

```shell
/workspace/develop/dreambooth# ./launch.sh
The following values were not passed to `accelerate launch` and had defaults used instead:
        `--num_cpu_threads_per_process` was set to `8` to improve out-of-box performance
To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
For effortless bug reporting copy-paste your error into this form: https://docs.google.com/forms/d/e/1FAIpQLScPB8emS3Thkp66nvqwmjTEgxp8Y9ufuWTzFyr9kJ5AoI47dQ/viewform?usp=sf_link
================================================================================
/opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/cuda_setup/paths.py:86: UserWarning: /opt/conda/envs/huggingface did not contain libcudart.so as expected! Searching further paths...
  warn(
/opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/cuda_setup/paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('/usr/local/nvidia/lib'), PosixPath('/usr/local/cuda/compat/lib'), PosixPath('/usr/local/nvidia/lib64')}
  warn(
/opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/cuda_setup/paths.py:98: UserWarning: /opt/conda/lib/python3.8/site-packages/torch/lib:/opt/conda/lib/python3.8/site-packages/torch_tensorrt/lib:/usr/local/cuda/compat/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64 did not contain libcudart.so as expected! Searching further paths...
  warn(
/opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/cuda_setup/paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('CompVis/stable-diffusion-v1-4')}
  warn(
/opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/cuda_setup/paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('41091'), PosixPath('http'), PosixPath('//172.30.0.1')}
  warn(
/opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/cuda_setup/paths.py:20: UserWarning: WARNING: The following directories listed in your path were found to be non-existent: {PosixPath('socks5'), PosixPath('1090'), PosixPath('//172.30.0.1')}
  warn(
CUDA_SETUP: WARNING! libcudart.so not found in any environmental path. Searching /usr/local/cuda/lib64...
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /opt/conda/envs/huggingface/lib/python3.8/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Caching latents: 100%|██████████████████████████████████████████████████████████████████| 12/12 [00:05<00:00,  2.40it/s]
Steps:   0%|                                                                                    | 0/800 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_dreambooth.py", line 658, in <module>
    main()
  File "train_dreambooth.py", line 618, in main
    accelerator.backward(loss)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/accelerate/accelerator.py", line 882, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/torch/_tensor.py", line 402, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/torch/autograd/function.py", line 253, in apply
    return user_fn(self, *args)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/torch/utils/checkpoint.py", line 151, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/torch/autograd/__init__.py", line 191, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 12.00 GiB total capacity; 9.04 GiB already allocated; 384.22 MiB free; 10.48 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Steps:   0%|                                                                                    | 0/800 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/opt/conda/envs/huggingface/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/opt/conda/envs/huggingface/lib/python3.8/site-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/opt/conda/envs/huggingface/bin/python3.8', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--use_auth_token', '--instance_data_dir=/workspace/develop/huggingface-diffusers/dreambooth/data/alvan', '--class_data_dir=/workspace/develop/huggingface-diffusers/dreambooth/data/dog', '--output_dir=/workspace/develop/huggingface-diffusers/dreambooth/models/dog2', '--with_prior_preservation', '--prior_loss_weight=1.0', '--instance_prompt=photo of sks dog', '--class_prompt=photo of a dog', '--seed=3434554', '--resolution=512', '--center_crop', '--train_batch_size=1', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=5e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=12', '--sample_batch_size=4', '--max_train_steps=800']' returned non-zero exit status 1.
```

### System Info

- `diffusers` version: 0.4.0.dev0
- Platform: Linux-5.15.62.1-microsoft-standard-WSL2-x86_64-with-glibc2.10
- Python version: 3.8.13
- PyTorch version (GPU?): 1.13.0a0+d321be6 (True)
- Huggingface_hub version: 0.9.1
- Transformers version: 4.22.2
- Using GPU in script?: <yes>
- Using distributed or parallel set-up in script?: <no>

**Comment by ShivamShrirao** [comment]
Hey, how did you install diffusers ?

**Comment by weicao0** [comment]
> Hey, how did you install diffusers ? Also was xformers installed successfully for you ?

yes, I installed diffusers and xformer via pip.
# pip list | grep diffusers
diffusers                     0.4.0.dev0
# pip list | grep xformers
xformers                      0.0.13

Actually I have generated some images in CLASS_DIR.

**Comment by ShivamShrirao** [comment]
You need to install diffusers via with `pip install git+https://github.com/ShivamShrirao/diffusers`

**Comment by weicao0** [comment]
https://pastebin.com/uE1WcSxD
