### ISSUE TITLE
Runtime Errro

### ISSUE THREAD

**Issue by mustafakucuk0** [ShivamShrirao/diffusers#82]
### Describe the bug

As I stated in the bug https://github.com/ShivamShrirao/diffusers/issues/39#issue-1413568034, the code still throws this error. I tried everything, literally everything but there was no good end for me. The only fix for this error was to set up the python environment and install "diffusers" package with conda again. But it does not make any sense. 

Do I have to setup everything including the environment anytime I want to train again?

### Logs

```shell
File "train_dreambooth.py", line 765, in <module>
    main()
  File "train_dreambooth.py", line 712, in main
    noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/deepspeed/utils/nvtx.py", line 11, in wrapped_fn
    return func(*args, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/deepspeed/runtime/engine.py", line 1666, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_2d_condition.py", line 299, in forward
    encoder_hidden_states=encoder_hidden_states,
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 559, in forward
    create_custom_forward(attn), hidden_states, encoder_hidden_states
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 235, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/utils/checkpoint.py", line 96, in forward
    outputs = run_function(*args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/unet_blocks.py", line 553, in custom_forward
    return module(*inputs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 169, in forward
    hidden_states = block(hidden_states, context=context)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 218, in forward
    hidden_states = self.attn1(self.norm1(hidden_states)) + hidden_states
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/diffusers/models/attention.py", line 297, in forward
    return self.to_out(hidden_states)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
Steps:   0%|                                           | 0/5000 [00:00<?, ?it/s]
[2022-10-27 01:53:12,842] [INFO] [launch.py:286:sigkill_handler] Killing subprocess 15441
[2022-10-27 01:53:12,858] [ERROR] [launch.py:292:sigkill_handler] ['/home/lm/miniconda3/envs/dreambooth/bin/python', '-u', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=stable_diffusion_weights/sks', '--with_prior_preservation', '--prior_loss_weight=1.0', '--resolution=512', '--train_batch_size=1', '--mixed_precision=fp16', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=1', '--max_train_steps=5000', '--save_interval=1250', '--save_sample_prompt=photo of sks idiltavsanli', '--concepts_list=concepts_list.json'] exits with return code = 1
Traceback (most recent call last):
  File "/home/lm/miniconda3/envs/dreambooth/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/accelerate/commands/launch.py", line 827, in launch_command
    deepspeed_launcher(args)
  File "/home/lm/miniconda3/envs/dreambooth/lib/python3.7/site-packages/accelerate/commands/launch.py", line 540, in deepspeed_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['deepspeed', '--no_local_rank', '--num_gpus', '1', 'train_dreambooth.py', '--pretrained_model_name_or_path=CompVis/stable-diffusion-v1-4', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=stable_diffusion_weights/sks', '--with_prior_preservation', '--prior_loss_weight=1.0', '--resolution=512', '--train_batch_size=1', '--mixed_precision=fp16', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--learning_rate=1e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=1', '--max_train_steps=5000', '--save_interval=1250', '--save_sample_prompt=photo of sks idiltavsanli', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.
```

### System Info

- `diffusers` version: 0.7.0.dev0
- Platform: Linux-5.15.0-52-generic-x86_64-with-debian-bullseye-sid
- Python version: 3.7.13
- PyTorch version (GPU?): 1.12.1 (True)
- Huggingface_hub version: 0.10.1
- Transformers version: 4.23.1
- Using GPU in script?: Yes - RTX 3080TI
- Using distributed or parallel set-up in script?: No

**Comment by ShivamShrirao** [comment]
Diffusers should be installed with `pip install git+https://github.com/ShivamShrirao/diffusers.git` for my fork, not conda. Conda package is different.
Also if you are using deepspeed, I haven't verified it and won't be able to help with it. For deepspeed the main huggingface repo will be more helpful.

**Comment by mustafakucuk0** [comment]
Hello Shivam,

I tried your diffuser package in the first place. But it throws the above error. I think this error is about deepspeed package. I could not come up with a solution so far.

**Comment by Alx-AI** [comment]
Running into the same issue without modifying anything on the colab as well. 
Happens when generating class images:

`Generating class images:   0% 0/50 [00:06<?, ?it/s]
Traceback (most recent call last):
  File "train_dreambooth.py", line 824, in <module>
    main(args)
  File "train_dreambooth.py", line 475, in main
    images = pipeline(example["prompt"]).images
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipelines/stable_diffusion/pipeline_stable_diffusion.py", line 389, in __call__
    noise_pred = self.unet(latent_model_input, t, encoder_hidden_states=text_embeddings).sample
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_condition.py", line 310, in forward
    encoder_hidden_states=encoder_hidden_states,
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/unet_2d_blocks.py", line 598, in forward
    hidden_states = attn(hidden_states, encoder_hidden_states=encoder_hidden_states).sample
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 204, in forward
    hidden_states = block(hidden_states, context=encoder_hidden_states, timestep=timestep)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 406, in forward
    hidden_states = self.attn1(norm_hidden_states) + hidden_states
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/models/attention.py", line 503, in forward
    hidden_states = self.to_out[0](hidden_states)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: expected scalar type Half but found Float
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/accelerate_cli.py", line 43, in main
    args.func(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 837, in launch_command
    simple_launcher(args)
  File "/usr/local/lib/python3.7/dist-packages/accelerate/commands/launch.py", line 354, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', 'train_dreambooth.py', '--pretrained_model_name_or_path=runwayml/stable-diffusion-v1-5', '--pretrained_vae_name_or_path=stabilityai/sd-vae-ft-mse', '--output_dir=/content/stable_diffusion_weights/zwx', '--revision=fp16', '--with_prior_preservation', '--prior_loss_weight=1.0', '--seed=1337', '--resolution=512', '--train_batch_size=1', '--train_text_encoder', '--mixed_precision=fp16', '--use_8bit_adam', '--gradient_accumulation_steps=1', '--learning_rate=4e-6', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--num_class_images=50', '--sample_batch_size=1', '--max_train_steps=1000', '--save_interval=10000', '--save_sample_prompt=photo of ~MrBeast wearing Noggles, beautiful breath taking', '--concepts_list=concepts_list.json']' returned non-zero exit status 1.`

**Comment by feffy380** [comment]
Same error as @Alx-AI, also with colab. Installing commit 3cb0dbe8e407cffbba242ed3412e8359f34d9a33 instead of main seems to work and I trained a model yesterday, so the problem was introduced by a recent commit

**Comment by ShivamShrirao** [comment]
@feffy380 had a strange issue with things not working in colab, but working locally, Fixed now 3a21df300312708dbc1304633d6a96280043aa31
